/**
 * @file atoms.hpp
 * @brief X11 atom related symbols.
 * @author Alexander Rothman <gnomesort@megate.ch>
 * @date 2023
 * @copyright AGPL-3.0+
 */
#ifndef OBERON_INTERNAL_LINUX_X11_ATOMS_HPP
#define OBERON_INTERNAL_LINUX_X11_ATOMS_HPP

#define OBERON_INTERNAL_LINUX_X11_ATOM(name) OBERON_INTERNAL_LINUX_X11_ATOM_NAME(name, #name)

/**
 * @def OBERON_INTERNAL_LINUX_X11_ATOMS
 * @brief A mapping of symbolic names to X11 atom name strings.
 */
#define OBERON_INTERNAL_LINUX_X11_ATOMS \
  OBERON_INTERNAL_LINUX_X11_ATOM(WM_NAME) \
  OBERON_INTERNAL_LINUX_X11_ATOM(WM_PROTOCOLS) \
  OBERON_INTERNAL_LINUX_X11_ATOM(WM_DELETE_WINDOW) \
  OBERON_INTERNAL_LINUX_X11_ATOM(WM_TAKE_FOCUS) \
  OBERON_INTERNAL_LINUX_X11_ATOM(WM_CLIENT_LEADER) \
  OBERON_INTERNAL_LINUX_X11_ATOM(WM_HINTS) \
  OBERON_INTERNAL_LINUX_X11_ATOM(WM_NORMAL_HINTS) \
  OBERON_INTERNAL_LINUX_X11_ATOM(WM_STATE) \
  OBERON_INTERNAL_LINUX_X11_ATOM(WM_CLIENT_MACHINE) \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_PID, "_NET_WM_PID") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_NAME, "_NET_WM_NAME") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_PING, "_NET_WM_PING") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_SYNC_REQUEST, "_NET_WM_SYNC_REQUEST") \
  OBERON_INTERNAL_LINUX_X11_ATOM(UTF8_STRING) \
  OBERON_INTERNAL_LINUX_X11_ATOM(WM_CLASS) \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE, "_NET_WM_STATE") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_MODAL, "_NET_WM_STATE_MODAL") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_STICKY, "_NET_WM_STATE_STICKY") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_MAXIMIZED_VERT, "_NET_WM_STATE_MAXIMIZED_VERT") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_MAXIMIZED_HORZ, "_NET_WM_STATE_MAXIMIZED_HORZ") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_SHADED, "_NET_WM_STATE_SHADED") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_SKIP_TASKBAR, "_NET_WM_STATE_SKIP_TASKBAR") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_SKIP_PAGER, "_NET_WM_STATE_SKIP_PAGER") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_HIDDEN, "_NET_WM_STATE_HIDDEN") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_FULLSCREEN, "_NET_WM_STATE_FULLSCREEN") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_ABOVE, "_NET_WM_STATE_ABOVE") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_BELOW, "_NET_WM_STATE_BELOW") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_STATE_DEMANDS_ATTENTION, "_NET_WM_STATE_DEMANDS_ATTENTION") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_WM_BYPASS_COMPOSITOR, "_NET_WM_BYPASS_COMPOSITOR") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(NET_FRAME_EXTENTS, "_NET_FRAME_EXTENTS") \
  OBERON_INTERNAL_LINUX_X11_ATOM_NAME(OBERON_SYSTEM_SIGNAL, "_OBERON_SYSTEM_SIGNAL")

/**
 * @def OBERON_INTERNAL_LINUX_X11_SYSTEM_SIGNALS
 * @brief Signal constants that might be associated with the `OBERON_SYSTEM_SIGNAL` atom.
 */
#define OBERON_INTERNAL_LINUX_X11_SYSTEM_SIGNALS \
  OBERON_INTERNAL_LINUX_X11_SYSTEM_SIGNAL(QUIT)

namespace oberon::internal::linux::x11 {

/// @cond
#define OBERON_INTERNAL_LINUX_X11_ATOM_NAME(name, str) name##_ATOM,
/// @endcond

  /**
   * @enum atom
   * @brief Symbolic constants for X11 atoms.
   */
  enum atom {
    OBERON_INTERNAL_LINUX_X11_ATOMS
    MAX_ATOM
  };

#undef OBERON_INTERNAL_LINUX_X11_ATOM_NAME

/// @cond
#define OBERON_INTERNAL_LINUX_X11_SYSTEM_SIGNAL(name) name##_SYSTEM_SIGNAL,
/// @endcond

  /**
   * @enum system_signal
   * @brief Symbolic constants for Oberon's internal signals.
   */
  enum system_signal {
    OBERON_INTERNAL_LINUX_X11_SYSTEM_SIGNALS
    MAX_SYSTEM_SIGNAL
  };
#undef OBERON_INTERNAL_LINUX_X11_SYSTEM_SIGNAL

}

#endif
