/**
 * @file x11-atoms.hpp
 * @brief Defines macros related to X11 atoms.
 * @author Alexander Rothman <gnomesort@megate.ch>
 * @date 2023
 * @copyright AGPL-3.0+
 */
#ifndef OBERON_LINUX_X11_ATOMS_HPP
#define OBERON_LINUX_X11_ATOMS_HPP

#include "../types.hpp"

/// @cond
#define OBERON_LINUX_X_ATOM(name) OBERON_LINUX_X_ATOM_NAME(name, #name)
/// @endcond

/**
 * @def OBERON_LINUX_X_ATOMS
 * @brief A mapping of symbolic names to X11 atom name strings.
 */
#define OBERON_LINUX_X_ATOMS \
  OBERON_LINUX_X_ATOM(WM_NAME) \
  OBERON_LINUX_X_ATOM(WM_PROTOCOLS) \
  OBERON_LINUX_X_ATOM(WM_DELETE_WINDOW) \
  OBERON_LINUX_X_ATOM(WM_TAKE_FOCUS) \
  OBERON_LINUX_X_ATOM(WM_NORMAL_HINTS) \
  OBERON_LINUX_X_ATOM(WM_CLIENT_MACHINE) \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_PID, "_NET_WM_PID") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_NAME, "_NET_WM_NAME") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_PING, "_NET_WM_PING") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_SYNC_REQUEST, "_NET_WM_SYNC_REQUEST") \
  OBERON_LINUX_X_ATOM(UTF8_STRING) \
  OBERON_LINUX_X_ATOM(WM_CLASS) \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE, "_NET_WM_STATE") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_MODAL, "_NET_WM_STATE_MODAL") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_STICKY, "_NET_WM_STATE_STICKY") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_MAXIMIZED_VERT, "_NET_WM_STATE_MAXIMIZED_VERT") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_MAXIMIZED_HORZ, "_NET_WM_STATE_MAXIMIZED_HORZ") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_SHADED, "_NET_WM_STATE_SHADED") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_SKIP_TASKBAR, "_NET_WM_STATE_SKIP_TASKBAR") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_SKIP_PAGER, "_NET_WM_STATE_SKIP_PAGER") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_HIDDEN, "_NET_WM_STATE_HIDDEN") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_FULLSCREEN, "_NET_WM_STATE_FULLSCREEN") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_ABOVE, "_NET_WM_STATE_ABOVE") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_BELOW, "_NET_WM_STATE_BELOW") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_STATE_DEMANDS_ATTENTION, "_NET_WM_STATE_DEMANDS_ATTENTION") \
  OBERON_LINUX_X_ATOM_NAME(NET_WM_BYPASS_COMPOSITOR, "_NET_WM_BYPASS_COMPOSITOR") \
  OBERON_LINUX_X_ATOM_NAME(NET_FRAME_EXTENTS, "_NET_FRAME_EXTENTS")

namespace oberon::linux {

/// @cond
#define OBERON_LINUX_X_ATOM_NAME(name, str) OBERON_LINUX_X_ATOM_##name,
/// @endcond

  /**
   * @brief An enumeration of X11 atoms
   */
  enum x_atom_name : usize {
    OBERON_LINUX_X_ATOMS
    OBERON_LINUX_X_ATOM_MAX
  };

/// @cond
#undef OBERON_LINUX_X_ATOM_NAME
/// @endcond

}

#endif
